# Generated by Django 4.1 on 2022-09-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cosas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
