# Generated by Django 4.1 on 2022-09-02 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projecto', '0002_cosas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cosas',
        ),
    ]
