# Generated by Django 4.1 on 2022-09-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projecto', '0003_delete_cosas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='prods',
        ),
    ]
