# Generated by Django 4.1 on 2022-09-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projecto', '0006_alter_prods_producto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='prods',
            new_name='Productos',
        ),
    ]
