# Generated by Django 4.1 on 2022-09-02 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projecto', '0005_remove_prods_producto'),
        ('projecto', '0007_rename_prods_productos'),
    ]

    operations = [
    ]
